Adding Copyable feature
YieldStudio/nova-phone-field pull request #4
Opened 2023-01-17 21:57 UTC by ch-hamzzyy

2023-01-20 00:06 UTC, JamesHemery commented
Hi @ch-hamzzyy 

I'll test this tomorrow

2023-01-22 22:45 UTC, JamesHemery requested changes

2023-01-22 22:45 UTC, JamesHemery commented on resources/js/components/DetailField.vue
> +    <PanelItem :index="index" :field="field">
I think we need to copy the unmasked value (without spaces), so you can copy the nova components `js/fields/Detail/EmailField.vue`

2023-01-22 22:45 UTC, JamesHemery commented on resources/js/components/IndexField.vue
> +    <div :class="`text-${field.textAlign}`">
I think we need to copy the unmasked value (without spaces), so you can copy the nova components `js/fields/Index/EmailField.vue`

2023-02-07 16:28 UTC, ch-hamzzyy commented
I Don't think we have to do these things because of the changes, mine is working perfectly.

2023-02-17 17:12 UTC, JamesHemery commented
> I Don't think we have to do these things because of the changes, mine is working perfectly.

When I copy phone number, I don't want to get spaces. Just change the copied value to unmasked value and I'll merge.

2023-07-19 19:02 UTC, JamesHemery commented
Replaced by #4

2023-07-19 19:02 UTC, closed without merging